# Generated by Django 4.1.6 on 2023-02-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(blank=True, max_length=12, null=True)),
                ('originaltitle', models.CharField(blank=True, max_length=450, null=True)),
                ('runtimeminutes', models.FloatField(blank=True, default=0.0, null=True)),
                ('averagerating', models.FloatField(blank=True, default=0.0, null=True)),
                ('numvotes', models.IntegerField(blank=True, null=True)),
                ('movie_features', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='films',
            index=models.Index(fields=['originaltitle'], name='core_films_origina_aa7dce_idx'),
        ),
    ]
